# Generated by Django 6.1.1 on 2026-10-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyResource',
            fields=[
                ('resource_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('resource_type', models.CharField(choices=[('Reviewer', 'Reviewer'), ('Notes', 'Notes'), ('Learning Material', 'Learning Material'), ('Study Guide', 'Study Guide')], default='Notes', max_length=30)),
                ('author_uploader', models.CharField(max_length=100)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/files/')),
                ('external_link', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Archived', 'Archived')], default='Active', max_length=20)),
            ],
            options={
                'verbose_name': 'Study Resource',
                'verbose_name_plural': 'Study Resources',
            },
        ),
    ]
